server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 250407
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fast_food
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
debug: true


