
server:
  port: 8089
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: CLIENTSERVICE
  datasource:
    username: postgres
    password: 250407
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fast_food
  jpa:
    show-sql: true
debug: true
